import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Row Level Security assumptions.
 *
 * These tests read the migrations rather than a live database, so they run in
 * CI without Postgres. They pin the structural guarantees the application
 * relies on, most importantly that every table has RLS enabled, and that the
 * encrypted credential table has no policy at all, which denies it to every
 * browser-facing role.
 */

const MIGRATIONS_DIR = join(process.cwd(), "supabase", "migrations");

function readMigration(name: string): string {
  return readFileSync(join(MIGRATIONS_DIR, name), "utf8");
}

const schemaSql = readMigration("20260101000000_core_schema.sql");
const functionsSql = readMigration("20260101000001_functions.sql");
const rlsSql = readMigration("20260101000002_rls.sql");

/** Every `create table public.x` in the schema migration. */
function declaredTables(sql: string): string[] {
  return [...sql.matchAll(/create table public\.(\w+)/g)].map((match) => match[1] ?? "");
}

/** Every table with `alter table public.x enable row level security`. */
function rlsEnabledTables(sql: string): string[] {
  return [...sql.matchAll(/alter table public\.(\w+) enable row level security/g)].map(
    (match) => match[1] ?? "",
  );
}

describe("schema", () => {
  it("declares every core table the product depends on", () => {
    const tables = declaredTables(schemaSql);

    for (const required of [
      "profiles",
      "organizations",
      "organization_members",
      "projects",
      "project_settings",
      "subscriptions",
      "billing_events",
      "crawls",
      "crawl_pages",
      "page_links",
      "page_issues",
      "page_scores",
      "project_scores",
      "competitors",
      "prompts",
      "prompt_tags",
      "ai_runs",
      "ai_citations",
      "ai_competitor_mentions",
      "search_console_connections",
      "search_console_metrics",
      "bing_connections",
      "bing_metrics",
      "analytics_connections",
      "pagespeed_runs",
      "opportunities",
      "reports",
      "integration_credentials",
      "usage_events",
      "audit_logs",
    ]) {
      expect(tables, `missing table: ${required}`).toContain(required);
    }
  });

  it("uses UUID primary keys generated by the database", () => {
    // Every table except the two keyed by a foreign id uses gen_random_uuid().
    const generatedCount = (schemaSql.match(/default gen_random_uuid\(\)/g) ?? []).length;
    expect(generatedCount).toBeGreaterThan(25);
  });

  it("gives every table a created_at timestamp", () => {
    const tableCount = declaredTables(schemaSql).length;
    const createdAtCount = (schemaSql.match(/created_at timestamptz not null default now\(\)/g) ?? [])
      .length;
    // rate_limit_counters is the one table keyed purely by its window.
    expect(createdAtCount).toBeGreaterThanOrEqual(tableCount - 1);
  });

  it("stores money in the smallest currency unit", () => {
    expect(schemaSql).toMatch(/price_minor bigint not null/);
    expect(schemaSql).toMatch(/amount_minor bigint/);
  });

  it("makes webhook replays impossible via a unique provider event id", () => {
    expect(schemaSql).toMatch(/provider_event_id text unique/);
  });

  it("makes job enqueueing idempotent via a unique key", () => {
    expect(schemaSql).toMatch(/idempotency_key text unique/);
  });
});

describe("row level security", () => {
  it("enables RLS on every table declared in the schema", () => {
    const tables = declaredTables(schemaSql);
    const enabled = rlsEnabledTables(rlsSql);

    for (const table of tables) {
      expect(enabled, `RLS not enabled on ${table}`).toContain(table);
    }
  });

  it("denies integration_credentials to every client role by giving it no policy", () => {
    // RLS on with zero policies is a deny-all for anon and authenticated.
    expect(rlsSql).toMatch(/alter table public\.integration_credentials enable row level security/);
    expect(rlsSql).not.toMatch(/create policy \w+ on public\.integration_credentials/);
    expect(rlsSql).toMatch(/revoke all on public\.integration_credentials from authenticated, anon/);
  });

  it("denies rate_limit_counters to every client role", () => {
    expect(rlsSql).not.toMatch(/create policy \w+ on public\.rate_limit_counters/);
    expect(rlsSql).toMatch(/revoke all on public\.rate_limit_counters from authenticated, anon/);
  });

  it("makes derived analysis tables read-only to clients", () => {
    // Crawl output, scores and AI runs are written only by service-role jobs.
    for (const table of [
      "crawl_pages",
      "page_issues",
      "page_scores",
      "project_scores",
      "ai_runs",
      "ai_citations",
      "ai_competitor_mentions",
    ]) {
      const selectPolicy = new RegExp(`create policy \\w+ on public\\.${table}\\s+for select`);
      expect(rlsSql, `${table} needs a select policy`).toMatch(selectPolicy);

      const writePolicy = new RegExp(
        `create policy \\w+ on public\\.${table}\\s+for (all|insert|update|delete)`,
      );
      expect(rlsSql, `${table} must not be client-writable`).not.toMatch(writePolicy);
    }
  });

  it("scopes project data to organization membership", () => {
    expect(rlsSql).toMatch(/using \(public\.is_project_member\(project_id\)\)/);
    expect(rlsSql).toMatch(/using \(public\.is_org_member\(organization_id\)/);
  });

  it("requires a write-capable role for user-managed tables", () => {
    for (const table of ["prompts", "competitors", "project_settings"]) {
      const pattern = new RegExp(
        `create policy \\w+ on public\\.${table}\\s+for all[\\s\\S]{0,120}can_write_project`,
      );
      expect(rlsSql, `${table} write policy must require can_write_project`).toMatch(pattern);
    }
  });

  it("restricts notifications to their owner", () => {
    expect(rlsSql).toMatch(/create policy notifications_select on public\.notifications/);
    expect(rlsSql).toMatch(/using \(user_id = auth\.uid\(\)\)/);
  });

  it("restricts system errors to platform admins", () => {
    expect(rlsSql).toMatch(
      /create policy system_errors_select_admin on public\.system_errors[\s\S]{0,120}is_platform_admin/,
    );
  });

  it("never grants clients insert or delete on billing tables", () => {
    expect(rlsSql).not.toMatch(/grant insert[^;]*public\.subscriptions/);
    expect(rlsSql).not.toMatch(/grant insert[^;]*public\.billing_events/);
  });
});

describe("security definer helpers", () => {
  it("defines the membership helpers RLS policies depend on", () => {
    for (const fn of [
      "is_org_member",
      "has_org_role",
      "is_project_member",
      "can_write_project",
      "is_platform_admin",
    ]) {
      expect(functionsSql, `missing helper: ${fn}`).toMatch(
        new RegExp(`create or replace function public\\.${fn}`),
      );
    }
  });

  it("marks membership helpers security definer so policies do not recurse", () => {
    // Without SECURITY DEFINER, a policy on organization_members that calls
    // is_org_member would re-enter its own policy and deadlock the check.
    const helperBlock = functionsSql.slice(
      functionsSql.indexOf("function public.is_org_member"),
      functionsSql.indexOf("function public.handle_new_user"),
    );
    const definerCount = (helperBlock.match(/security definer/g) ?? []).length;
    expect(definerCount).toBeGreaterThanOrEqual(5);
  });

  it("pins search_path on security definer functions", () => {
    // A mutable search_path on a SECURITY DEFINER function is a privilege
    // escalation vector.
    const definerCount = (functionsSql.match(/security definer/g) ?? []).length;
    const searchPathCount = (functionsSql.match(/set search_path = public, pg_temp/g) ?? []).length;
    expect(searchPathCount).toBe(definerCount);
  });

  it("reserves the privileged job and rate-limit RPCs for the service role", () => {
    expect(functionsSql).toMatch(/revoke all on function public\.claim_jobs[^;]*from public/);
    expect(functionsSql).toMatch(/grant execute on function public\.claim_jobs[^;]*to service_role/);
    expect(functionsSql).toMatch(
      /grant execute on function public\.consume_rate_limit[^;]*to service_role/,
    );
  });

  it("bootstraps a profile, organization and membership for every new user", () => {
    expect(functionsSql).toMatch(/create trigger on_auth_user_created/);
    expect(functionsSql).toMatch(/insert into public\.profiles/);
    expect(functionsSql).toMatch(/insert into public\.organizations/);
    expect(functionsSql).toMatch(/insert into public\.organization_members/);
  });
});
